### ISSUE TITLE
no files found

### ISSUE THREAD

**Issue by Xinming9606** [drboothtj/getphylo#2]
Hi! Thanks for developing this tool! I would love to use it to build a phylogenetic tree of my genomes, but I keep getting issues. It shows no files found in the folder'BGI_genomes/genebank', but I am certain I have few *.gb files. Another question is if this support other formats? like fna? Thank you!
$ getphylo -g '/home/xuaxi/BGI_genomes/genebank/*.gb'
[16:53:07] INFO      : Running getphylo version 0.1.0.
[16:53:07] ERROR     : ALERT: The directory /home/xuaxi/output/fasta already exists.

~$ getphylo -l INFO
[16:53:29] INFO      : Running getphylo version 0.1.0.
[16:53:29] ERROR     : No files found in *.gbk.

**Comment by drboothtj** [comment]
Thanks for getting in touch!

These are two separate errors. I will explain them below.

**"ERROR : ALERT: The directory /home/xuaxi/output/fasta already exists."** 
As the error indicates you already have an output directory. To avoid overwriting files unintentionally, getphylo will not write into an output directory if a directory with the same name already exists. To avoid this you should either:

a. delete the output directory before starting the run (`rm -r output; getphylo -g '/home/xuaxi/BGI_genomes/genebank/*.gb'`) or;
b. point getphylo to a new output directory: `getphylo -g '/home/xuaxi/BGI_genomes/genebank/*.gb' -o new_output_dir`.

In both cases, beware the missing wildcard (*)!

"**[16:53:29] ERROR : No files found in *.gbk.**"
By default getphylo will use the search string `*.gbk`. So if your files end in `.gb` they will not be found by getphylo under default settings. In your previous example, you also missed the wildcard character so be careful that your search string is correct. If you are not sure, you should check that `ls my_search_string` shows the result you desire.

Thanks for raising these issues. I will add them to: https://github.com/drboothtj/getphylo/wiki/5.-FAQs-and-Common-Errors

If you have any other issues don't hesitate to reach out and thanks for using getphylo!

**Comment by drboothtj** [comment]
I will now mark this as resolved. Please let me know if you have any persisting issues.

**Comment by Xinming9606** [comment]
Thanks a lot for your reply :)
