### ISSUE TITLE
Incorrect argument names for Diamond in diamond.py

### ISSUE THREAD

**Issue by jordiweijers** [drboothtj/getphylo#5]
Hello,
I encountered an issue in the diamond.py script where certain arguments passed to the Diamond tool are not recognized. Specifically, the script uses --query_cover and --subject_cover as arguments, which are not accepted by Diamond. The correct argument names appear to be --query-cover and --subject-cover (with hyphens instead of underscores). The versions I have are diamond v2.1.10 and getphylo v0.3.0

**Comment by drboothtj** [comment]
Thanks for your detailed report.

You are correct and I have now fixed the issue. The new version is now also up on PyPI.

Thanks again for catching this issue - your input is very much appreciated!
